# Web Crawling Berita Detik

## Pendahuluan

Web crawling merupakan proses pengambilan data dari halaman web secara otomatis menggunakan program.

Pada praktikum ini, proses web crawling dilakukan menggunakan bahasa pemrograman Python untuk mengambil data berita dari situs Detik. Data yang dikumpulkan berasal dari dua kategori berita, yaitu **Sport** dan **Finance**.

Sumber data yang digunakan adalah:

- Sport: `https://sport.detik.com/`
- Finance: `https://finance.detik.com/`

Setiap berita yang berhasil dikumpulkan akan disimpan sebagai dataset dengan tiga atribut, yaitu:

- `id` — nomor identitas data
- `isi_berita` — isi atau teks berita
- `label` — kategori berita

Target pengumpulan data adalah **100 berita Sport dan 100 berita Finance**, sehingga diharapkan diperoleh maksimal **200 data berita**.

Dataset hasil crawling selanjutnya dapat digunakan untuk proses **text preprocessing, text mining, klasifikasi teks, dan machine learning**.

## 1. Import Library

Tahap pertama adalah mengimpor library yang dibutuhkan untuk proses web crawling.

Library yang digunakan terdiri dari:

- **Requests** untuk mengirim HTTP request dan mengambil halaman web.
- **BeautifulSoup** untuk membaca dan memproses struktur HTML.
- **CSV** untuk menyimpan hasil crawling ke dalam file CSV.
- **Time** untuk memberikan jeda antar-request.
- **URLJoin** untuk mengubah URL relatif menjadi URL lengkap.

Pada tahap ini program hanya mempersiapkan library dan belum melakukan proses crawling.

In [2]:
%pip install requests beautifulsoup4

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (4.15.0)
Collecting charset_normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.5.1-cp313-cp313-win_amd64.whl.metadata (46 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (from requests) (3.19)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (from beautifulsoup4) (4.16.0)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Using cached charset_normalizer-3.5.1-cp313-cp313-win_amd64.whl (199 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, charset_normalizer, certifi, requests
Successfully installed certifi-2026.7.22 charset_normalizer-3.5.1 requests-2.34.2 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import requests
from bs4 import BeautifulSoup
import csv
import time
from urllib.parse import urljoin

## 2. Menentukan HTTP Headers

HTTP headers digunakan untuk memberikan informasi tambahan ketika program melakukan request ke sebuah website.

Pada tahap ini digunakan `User-Agent` yang menyerupai browser. Hal tersebut membuat request memiliki informasi mengenai browser yang digunakan ketika mengakses halaman website.

Header ini nantinya akan digunakan pada setiap request selama proses crawling.

In [4]:
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/131.0.0.0 Safari/537.36"
    )
}

## 3. Membuat Session

`requests.Session()` digunakan untuk membuat session yang dapat digunakan berulang kali selama proses crawling.

Dengan menggunakan session, konfigurasi seperti `User-Agent` dapat diterapkan pada setiap request secara otomatis. Dengan demikian, kita tidak perlu menuliskan konfigurasi header berulang kali.

In [5]:
session = requests.Session()
session.headers.update(HEADERS)

## 4. Membuat Fungsi untuk Mengambil URL Artikel

Tahap berikutnya adalah membuat fungsi `ambil_url_artikel()` untuk mencari URL artikel dari halaman kategori berita.

Fungsi ini akan:

1. Membuka halaman kategori berita.
2. Membuka halaman indeks berikutnya jika jumlah artikel belum terpenuhi.
3. Membaca struktur HTML menggunakan BeautifulSoup.
4. Mencari seluruh link pada halaman.
5. Mengambil URL dari atribut `href`.
6. Mengubah URL relatif menjadi URL lengkap.
7. Memastikan URL berasal dari domain yang sesuai.
8. Memastikan URL merupakan URL artikel.
9. Menghindari URL yang sama atau duplikat.
10. Menghentikan proses jika jumlah URL yang dibutuhkan sudah terpenuhi.

Fungsi ini belum akan dijalankan sampai kita memanggilnya pada tahap berikutnya.

In [6]:
def ambil_url_artikel(url_kategori, domain, jumlah=100):
    """
    Mengambil URL artikel dari homepage dan
    halaman indeks sampai jumlah URL terpenuhi.
    """

    print(f"\nMengambil artikel dari: {url_kategori}")

    daftar_url = []
    halaman = 1

    while len(daftar_url) < jumlah:

        if halaman == 1:
            url = url_kategori
        else:
            url = f"{url_kategori.rstrip('/')}/indeks?page={halaman}"

        print(f"\nMengambil halaman {halaman}:")
        print(url)

        try:
            response = session.get(
                url,
                timeout=15
            )

            print("Status:", response.status_code)

        except requests.RequestException as error:
            print("Error:", error)
            halaman += 1
            continue

        if response.status_code != 200:
            print("Halaman gagal diakses.")
            halaman += 1
            continue

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        jumlah_sebelum = len(daftar_url)

        for link in soup.find_all("a", href=True):

            href = link["href"].strip()

            href = urljoin(url, href)

            if (
                domain in href
                and "/d-" in href
            ):

                href = href.split("#")[0]

                if href not in daftar_url:

                    daftar_url.append(href)

                    print(
                        f"  [{len(daftar_url)}/{jumlah}] "
                        f"{href}"
                    )

                if len(daftar_url) >= jumlah:
                    break

        jumlah_baru = len(daftar_url) - jumlah_sebelum

        print(
            f"Artikel baru dari halaman ini: "
            f"{jumlah_baru}"
        )

        if jumlah_baru == 0:
            print(
                "Tidak ada artikel baru di halaman ini."
            )

        halaman += 1

        time.sleep(1)

        if halaman > 30:
            print("Batas halaman tercapai.")
            break

    print("\n======================================")
    print(
        f"Total URL {domain}: "
        f"{len(daftar_url)}"
    )
    print("======================================")

    return daftar_url[:jumlah]

## 5. Menentukan URL Kategori Sport

Sebelum menjalankan fungsi crawling, kita menentukan alamat halaman kategori Sport yang akan digunakan sebagai sumber data.

Pada tahap ini belum dilakukan pengambilan 100 berita. Kita akan melakukan pengujian terlebih dahulu dengan jumlah data yang kecil untuk memastikan fungsi dapat berjalan dengan baik.

In [7]:
sport_url = "https://sport.detik.com/"

## 6. Pengujian Pengambilan URL Artikel

Sebelum melakukan crawling dalam jumlah besar, kita melakukan pengujian terlebih dahulu.

Pada pengujian ini hanya akan diambil **5 URL artikel** dari kategori Sport.

Pengujian ini bertujuan untuk memastikan bahwa program dapat mengakses halaman kategori dan menemukan URL artikel dengan benar.

Jika proses pengujian berhasil, jumlah data nantinya dapat ditingkatkan menjadi 100 artikel.

In [8]:
url_test = ambil_url_artikel(
    sport_url,
    "sport.detik.com",
    5
)

Mengambil artikel dari: https://sport.detik.com/

Mengambil halaman 1:
https://sport.detik.com/
Status: 200
  [1/5] https://sport.detik.com/raket/d-8653585/asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri
  [2/5] https://sport.detik.com/basket/d-8649812/derrick-michael-wujudkan-mimpi-masa-kecil-tampil-di-asian-games-2026
  [3/5] https://sport.detik.com/moto-gp/d-8652425/dokter-perkirakan-kondisi-lengan-marc-marquez-sekitar-50-persen
  [4/5] https://sport.detik.com/raket/d-8653493/tekad-alwi-farhan-lampaui-batas-di-asian-games-2026
  [5/5] https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
Artikel baru dari halaman ini: 5

======================================
Total URL sport.detik.com: 5
======================================

## 7. Membuat Fungsi untuk Mengambil Isi Berita

Setelah URL artikel berhasil diperoleh, tahap selanjutnya adalah mengambil isi dari setiap halaman artikel.

Fungsi `ambil_isi_berita()` digunakan untuk membuka halaman artikel dan mencari bagian HTML yang berisi isi berita.

Program menggunakan beberapa selector sebagai alternatif untuk menemukan bagian artikel.

Setelah bagian artikel ditemukan, beberapa elemen yang tidak diperlukan akan dihapus, seperti:

- `script`
- `style`
- `iframe`
- `img`
- `video`
- `figure`
- `button`

Setelah itu, teks berita diambil dan dirapikan sehingga spasi yang berlebihan dihilangkan.

Hasil akhirnya berupa teks berita yang dapat digunakan sebagai data.

In [9]:
def ambil_isi_berita(url):
    """
    Membuka halaman artikel dan mengambil isi berita.
    """

    try:

        response = session.get(
            url,
            timeout=15
        )

        if response.status_code != 200:

            print(
                "Gagal membuka:",
                response.status_code
            )

            return ""

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        selector_list = [
            ".detail__body-text",
            ".detail__body",
            "div.detail__body-text",
            "article"
        ]

        artikel = None

        for selector in selector_list:

            artikel = soup.select_one(selector)

            if artikel is not None:
                break

        if artikel is None:
            return ""

        for tag in artikel.find_all(
            [
                "script",
                "style",
                "iframe",
                "img",
                "video",
                "figure",
                "button"
            ]
        ):

            tag.decompose()

        isi = artikel.get_text(
            " ",
            strip=True
        )

        isi = " ".join(
            isi.split()
        )

        return isi

    except requests.RequestException as error:

        print(
            "Error:",
            error
        )

        return ""

## 8. Pengujian Pengambilan Isi Berita

Selanjutnya kita melakukan pengujian terhadap satu URL artikel yang sebelumnya telah ditemukan.

Tujuannya adalah memastikan bahwa fungsi `ambil_isi_berita()` berhasil menemukan dan mengambil teks dari halaman artikel.

Jika isi berita berhasil ditampilkan, fungsi tersebut dapat digunakan untuk memproses banyak artikel.

In [10]:
url_contoh = url_test[0]

isi_contoh = ambil_isi_berita(url_contoh)

print(isi_contoh)

Jakarta - Putri Kusuma Wardani percaya diri dengan komposisi beregu putri yang dipilih PBSI untuk Asian Games 2026. Dia juga menyebut chemistry satu sama lain sudah klop. Bulutangkis Indonesia mengirimkan 20 wakil untuk tampil di Aichi-Nagoya, 19 September hingga 4 Oktober mendatang. 10 Atlet di antaranya merupakan sektor beregu putri. Yaitu Putri KW, Thalita R. Wiryawan, Ni Kadek Dhinda, Mutiara Ayu Puspitasari, Rachel Allessya Rose, Febi Setianingrum, Febriana Dwipuji Kusuma, Meilysa Trias Puspitasari, Siti Fadia Silva Ramadhanti, dan Nita Violina Marwah. SCROLL TO CONTINUE WITH CONTENT Baca juga: Tekad Alwi Farhan Lampaui Batas di Asian Games 2026 Putri menilai komposisi skuad bulutangkis Indonesia yang mengombinasikan pemain senior dan junior, tidak menemukan kendala dalam membangun koneksi di dalam tim. ADVERTISEMENT Pengalaman berlaga bersama dalam beberapa kejuaraan beregu sebelumnya dinilai telah membentuk kekompakan antar-atlet. "Dengan tim komposisi yang ada cukup kuat sih. Kita juga sudah lumayan dua atau tiga kali beregu bersama-sama, jadi sudah ketemu chemistry-nya di antara satu dan yang lain, baik tunggal maupun ganda," kata Putri dalam keterangannya dikutip Selasa (8/9/2026). Tak hanya itu, seluruh rangkaian program latihan di Pelatnas sejauh ini berjalan dengan lancar dan kondusif. Sampai menjelang hari keberangkatan menuju Jepang, porsi latihan tim nasional kini lebih difokuskan pada penguatan di masing-masing sektor di bawah arahan tim pelatih. "Yang pasti, kekurangan dari pertandingan sebelumnya menuju pertandingan Asian Games lebih ditingkatkan lagi," tambahnya. Baca juga: Ini Dia 20 Pebulutangkis Indonesia di Asian Games 2026 Terkait peta persaingan di Asian Games 2026, Putri KW menilai kekuatan di sektor tunggal putri kawasan Asia tergolong sangat merata. Dia mewaspadai kekuatan para pemain dari negara-negara papan atas seperti China, Jepang, dan Korea Selatan. "Kalau kekuatan sendiri di Asian Games menurut aku cukup merata ya dari Asia sendiri, terutama dari China, Jepang, dan Korea Selatan sih cukup kuat," tuturnya. Pebulutangkis peringkat ke-7 dunia itu memasang target tinggi pada ajang Asian Games 2026. Secara pribadi, Putri berambisi untuk dapat melangkah hingga ke babak akhir dan berdiri di atas podium. Hal ini juga sejalan dengan target medali yang dicanangkan oleh PP PBSI. "Harapannya semoga tim bulu tangkis Indonesia bisa mendapatkan medali, dan terutama untuk pribadi aku sendiri, aku bisa menyumbangkan medali untuk Indonesia di ajang Asian Games," pungkas Putri. Lihat juga Video; Hong Kong Open 2024: Sabar/Reza dan Putri KW Tumbang di Final [Gambas:Video 20detik] (mcy/aff) ... Tautan telah disalin asian games 2026 putri kusuma wardani pbsi

## 9. Membuat Fungsi Crawling Kategori

Setelah fungsi untuk mengambil URL dan fungsi untuk mengambil isi berita berhasil dibuat dan diuji, kedua fungsi tersebut digunakan dalam satu fungsi utama, yaitu `crawling_kategori()`.

Fungsi ini bertugas melakukan crawling pada satu kategori berita.

Prosesnya adalah:

1. Mengambil URL artikel.
2. Membuka setiap URL artikel.
3. Mengambil isi berita.
4. Menyimpan isi berita.
5. Memberikan label sesuai kategori.
6. Memberikan jeda antar-request.
7. Menghentikan proses ketika jumlah data valid telah mencapai target.

Setiap data akan memiliki struktur:

```text
isi_berita → isi teks berita
label      → kategori berita

In [13]:

# 19. Code Cell — Fungsi Crawling

def crawling_kategori(
    url_kategori,
    domain,
    label,
    jumlah=100
):

    print("\n======================================")
    print(f"CRAWLING {label.upper()}")
    print("Target:", jumlah, "berita")
    print("======================================")

    urls = ambil_url_artikel(
        url_kategori,
        domain,
        jumlah
    )

    print(
        f"\nURL yang akan diproses: "
        f"{len(urls)}"
    )

    data = []

    for i, url in enumerate(
        urls,
        start=1
    ):

        print(
            f"\n[{i}/{len(urls)}] "
            f"Mengambil berita {label}..."
        )

        isi = ambil_isi_berita(url)

        if isi:

            data.append({
                "isi_berita": isi,
                "label": label
            })

            print(
                "✓ Berhasil | "
                f"{len(isi)} karakter"
            )

        else:

            print(
                "✗ Isi berita tidak ditemukan"
            )

        time.sleep(1)

        if len(data) >= jumlah:
            break

    print("\n======================================")
    print(
        f"Berita {label} berhasil: "
        f"{len(data)}"
    )
    print("======================================")

    return data

## 10. Menentukan Sumber Data

Pada tahap ini kita menentukan dua kategori berita yang akan digunakan sebagai sumber dataset.

Kategori pertama adalah **Sport**, sedangkan kategori kedua adalah **Finance**.

Kedua kategori akan diproses secara terpisah agar setiap berita dapat diberikan label yang sesuai.

In [14]:
sport_url = "https://sport.detik.com/"
finance_url = "https://finance.detik.com/"

## 11. Crawling Berita Sport

Pada tahap ini kita mulai melakukan crawling terhadap kategori **Sport**.

Program akan mengambil URL artikel dan kemudian mengambil isi dari setiap artikel.

Untuk pengujian awal, kita menggunakan target **5 berita** terlebih dahulu.

Jika proses berjalan dengan baik, target dapat diubah menjadi **100 berita**.

In [20]:
data_sport = crawling_kategori(
    sport_url,
    "sport.detik.com",
    "sport",
    5
)

======================================
CRAWLING SPORT
Target: 5 berita
======================================

Mengambil artikel dari: https://sport.detik.com/

Mengambil halaman 1:
https://sport.detik.com/
Status: 200
  [1/5] https://sport.detik.com/raket/d-8653585/asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri
  [2/5] https://sport.detik.com/basket/d-8649812/derrick-michael-wujudkan-mimpi-masa-kecil-tampil-di-asian-games-2026
  [3/5] https://sport.detik.com/moto-gp/d-8652425/dokter-perkirakan-kondisi-lengan-marc-marquez-sekitar-50-persen
  [4/5] https://sport.detik.com/raket/d-8653493/tekad-alwi-farhan-lampaui-batas-di-asian-games-2026
  [5/5] https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
Artikel baru dari halaman ini: 5

======================================
Total URL sport.detik.com: 5
======================================

URL yang akan diproses: 5

[1/5] Mengambil berita sport...
✓ Berhasil | 2720 karakter

[2/5] Mengambil berita sport...
✓ Berhasil | 2749 karakter

[3/5] Mengambil berita sport...
✓ Berhasil | 2191 karakter

[4/5] Mengambil berita sport...
✓ Berhasil | 2239 karakter

[5/5] Mengambil berita sport...
✓ Berhasil | 3619 karakter

======================================
Berita sport berhasil: 5
======================================

In [21]:
data_finance = crawling_kategori(
    finance_url,
    "finance.detik.com",
    "finance",
    5
)

======================================
CRAWLING FINANCE
Target: 5 berita
======================================

Mengambil artikel dari: https://finance.detik.com/

Mengambil halaman 1:
https://finance.detik.com/
Status: 200
  [1/5] https://finance.detik.com/berita-ekonomi-bisnis/d-8653106/bandara-soetta-husein-dibuka-lagi-radin-inten-masih-ditutup
  [2/5] https://finance.detik.com/berita-ekonomi-bisnis/d-8652990/pramono-mau-terbitkan-obligasi-purbaya-kalau-uangnya-banyak-buat-apa-utang
  [3/5] https://finance.detik.com/moneter/d-8652973/muncul-isu-gaji-asn-dipindah-ke-bank-bumn-purbaya-buka-suara
  [4/5] https://finance.detik.com/energi/d-8652949/terindikasi-isi-bbm-berulang-5-000-nomor-polisi-kendaraan-diajukan-blokir
  [5/5] https://finance.detik.com/berita-ekonomi-bisnis/d-8652862/7-bandara-ditutup-hingga-23-59-wib-ini-daftarnya
Artikel baru dari halaman ini: 5

======================================
Total URL finance.detik.com: 5
======================================

URL yang akan diproses: 5

[1/5] Mengambil berita finance...
✓ Berhasil | 2459 karakter

[2/5] Mengambil berita finance...
✓ Berhasil | 2758 karakter

[3/5] Mengambil berita finance...
✓ Berhasil | 2137 karakter

[4/5] Mengambil berita finance...
✓ Berhasil | 4664 karakter

[5/5] Mengambil berita finance...
✓ Berhasil | 2588 karakter

======================================
Berita finance berhasil: 5
======================================

In [23]:
data_sport = crawling_kategori(
    sport_url,
    "sport.detik.com",
    "sport",
    100
)

======================================
CRAWLING SPORT
Target: 100 berita
======================================

Mengambil artikel dari: https://sport.detik.com/

Mengambil halaman 1:
https://sport.detik.com/
Status: 200
  [1/100] https://sport.detik.com/raket/d-8653585/asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri
  [2/100] https://sport.detik.com/basket/d-8649812/derrick-michael-wujudkan-mimpi-masa-kecil-tampil-di-asian-games-2026
  [3/100] https://sport.detik.com/moto-gp/d-8652425/dokter-perkirakan-kondisi-lengan-marc-marquez-sekitar-50-persen
  [4/100] https://sport.detik.com/raket/d-8653493/tekad-alwi-farhan-lampaui-batas-di-asian-games-2026
  [5/100] https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
  [6/100] https://sport.detik.com/sport-lain/d-8654342/menuju-asian-games-2026-ketum-koi-tekankan-kolaborasi
  [7/100] https://sport.detik.com/sport-lain/d-8649149/timnas-voli-putra-dan-putri-indonesia-bidik-8-besar-asian-games-2026
  [8/100] https://sport.detik.com/sport-lain/d-8648160/pemanasan-timnas-basket-3x3-di-taiwan-jelang-asian-games-2026
  [9/100] https://sport.detik.com/sepakbola/uefa/d-8654326/liga-champions-inter-tersingkir-terlalu-awal-musim-lalu
  [10/100] https://sport.detik.com/sport-lain/d-8654586/ihr-2026-perluas-olahraga-pacuan-kuda-indonesia
  [11/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8654262/thailand-nggak-akan-tiru-naturalisasi-yang-dilakukan-vietnam
  [12/100] https://sport.detik.com/sepakbola/liga-inggris/d-8654327/arsenal-makin-pede-main-cantik
  [13/100] https://sport.detik.com/sepakbola/uefa/d-8654322/4-debutan-liga-champions-langsung-diuji-para-raksasa-eropa
  [14/100] https://sport.detik.com/sepakbola/bola-dunia/d-8654511/daftar-nominasi-ballon-dor-2026-rilis-ada-nama-messi
  [15/100] https://sport.detik.com/sepakbola/liga-inggris/d-8654323/ederson-angkat-bicara-soal-batal-gabung-ke-mu
  [16/100] https://sport.detik.com/sepakbola/uefa/d-8654330/pesan-haaland-buat-pesepakbola-muda-senyum-jangan-overthinking-jika-gagal
  [17/100] https://sport.detik.com/sepakbola/uefa/d-8654243/lautaro-martinez-kylian-mbappe-salah-satu-striker-terbaik
  [18/100] https://sport.detik.com/sepakbola/bola-dunia/d-8654437/daftar-nominasi-kopa-trophy-2026-cubarsi-yamal-kandidat-terkuat
  [19/100] https://sport.detik.com/sepakbola/uefa/d-8654258/madrid-vs-inter-vinicius-bersiap-hadapi-pertahanan-solid-si-ular
  [20/100] https://sport.detik.com/sepakbola/bola-dunia/d-8654411/nominasi-yashin-trophy-2026-vozinha-masuk-tak-ada-donnarumma
  [21/100] https://sport.detik.com/sepakbola/bola-dunia/d-8654386/daftar-nominasi-klub-dan-pelatih-terbaik-ballon-dor-2026
  [22/100] https://sport.detik.com/sepakbola/uefa/d-8653413/arsenal-bawa-rekor-apik-ke-markas-napoli-9-musim-tak-kalah-di-laga-pembuka
  [23/100] https://sport.detik.com/sepakbola/uefa/d-8653417/misi-menang-man-city-diadang-kandang-kukuh-porto
  [24/100] https://sport.detik.com/sepakbola/uefa/d-8654241/madrid-vs-inter-zamorano-prediksikan-laga-sulit-untuk-los-blancos
  [25/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8654321/sty-harap-persija-dapat-izin-hadapi-persib-di-jakarta
  [26/100] https://sport.detik.com/raket/d-8654261/nova-widianto-mulai-tangani-ganda-campuran-pelatnas-pbsi
  [27/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8654236/nestapa-vietnam-gagal-lolos-piala-asia-u-20-2027-sampai-degradasi
  [28/100] https://sport.detik.com/sepakbola/uefa/d-8653668/madrid-vs-inter-mourinho-tepikan-nostalgia-selama-90-menit
  [29/100] https://sport.detik.com/basket/d-8654249/timnas-basket-jadi-gelombang-pertama-datang-ke-asian-games-2026
  [30/100] https://sport.detik.com/sepakbola/liga-spanyol/d-8653678/aubameyang-hidup-lagi
  [31/100] https://sport.detik.com/sepakbola/uefa/d-8653679/6-data-fakta-madrid-vs-inter-dominasi-el-real
  [32/100] https://sport.detik.com/sepakbola/foto-sepakbola/d-8653662/chelsea-dan-sakit-tahunan
  [33/100] https://sport.detik.com/sepakbola/uefa/d-8653676/prediksi-supercomputer-real-madrid-vs-inter-los-blancos-favorit-kuat
  [34/100] https://sport.detik.com/sepakbola/liga-jerman/d-8653419/harry-kane-ingin-punya-karier-seawet-messi-dan-ronaldo
  [35/100] https://sport.detik.com/sepakbola/liga-inggris/d-8653673/ada-apa-dengan-garnacho
  [36/100] https://sport.detik.com/sepakbola/liga-spanyol/d-8653683/madrid-masih-adaptasi-dengan-gaya-main-mourinho
  [37/100] https://sport.detik.com/sepakbola/uefa/d-8653659/isak-lagi-panas-kini-kejar-gol-perdana-bersama-liverpool-di-liga-champions
  [38/100] https://sport.detik.com/sportstyle/d-8653975/nikmati-keseruan-lari-di-solo-run-fest-2026-beli-tiketnya-via-brimo
  [39/100] https://sport.detik.com/sepakbola/uefa/d-8653661/mourinho-heran-inter-milan-belum-juara-liga-champions-lagi
  [40/100] https://sport.detik.com/sepakbola/liga-spanyol/d-8653680/respons-pedas-mbappe-soal-dinilai-kurang-membantu-pertahanan-madrid
  [41/100] https://sport.detik.com/sepakbola/uefa/d-8653671/mu-comeback-ke-liga-champions-mainkan-laga-ke-300-lawan-klub-debutan
  [42/100] https://sport.detik.com/sepakbola/uefa/d-8653502/madrid-vs-inter-buruknya-rekor-nerazzurri-di-tanah-spanyol
  [43/100] https://sport.detik.com/basket/d-8653694/timnas-basket-putra-di-asian-games-2026-menangi-laga-pertama-dulu
  [44/100] https://sport.detik.com/sepakbola/liga-inggris/d-8653503/apa-benar-liverpool-incar-calvin-verdonk
  [45/100] https://sport.detik.com/sepakbola/uefa/d-8653499/prediksi-liga-champions-city-dortmund-madrid-dijagokan-menang-nanti-malam
  [46/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8653687/persib-pinjamkan-saddil-ramdani-ke-persebaya
  [47/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8653656/panpel-persija-masih-tunggu-izin-kepolisian-untuk-laga-vs-persib-di-gbk
  [48/100] https://sport.detik.com/sepakbola/uefa/d-8653416/head-to-head-madrid-vs-inter-milan-los-blancos-bagus-lawan-tim-italia
  [49/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8653569/piala-asia-u-20-timnas-indonesia-u-20-masuk-pot-berapa
  [50/100] https://sport.detik.com/sepakbola/uefa/d-8653404/kans-erling-haaland-ukir-rekor-baru-di-liga-champions
  [51/100] https://sport.detik.com/sepakbola/bola-dunia/d-8653399/bruno-fernandes-masuk-nominasi-ballon-dor-2026
  [52/100] https://sport.detik.com/sepakbola/uefa/d-8653402/jadwal-liga-champions-malam-ini-real-madrid-vs-inter-man-city-juga-main
Artikel baru dari halaman ini: 52

Mengambil halaman 2:
https://sport.detik.com/indeks?page=2
Status: 200
  [53/100] https://sport.detik.com/f1/d-8651436/hasil-f1-gp-italia-2026-kimi-antonelli-menang-mercedes-1-2
  [54/100] https://sport.detik.com/sport-lain/d-8651374/wec-2026-sean-gelael-balapan-di-austin-dini-hari-start-p7
  [55/100] https://sport.detik.com/moto-gp/d-8651046/ktm-suka-antusiasme-luca-marini
  [56/100] https://sport.detik.com/moto-gp/d-8650870/crutchlow-pilih-ai-ogura-jadi-favorit-setelah-marc-marquez-ini-alasannya
  [57/100] https://sport.detik.com/sport-lain/d-8650342/wec-2026-wrt-32-meraba-cota-dari-hasil-free-practice
  [58/100] https://sport.detik.com/raket/d-8650339/mens-world-tennis-championship-rafalentino-ethan-gagal-juara
  [59/100] https://sport.detik.com/sportstyle/d-8650215/minala-cup-padel-diikuti-lebih-dari-300-peserta
  [60/100] https://sport.detik.com/sport-lain/d-8650061/lewat-buku-eks-judoka-tuang-buah-pikiran-untuk-kemajuan-olahraga-nasional
  [61/100] https://sport.detik.com/basket/d-8649778/asian-games-2026-timnas-basket-masuk-grup-neraka-cdm-optimistis
  [62/100] https://sport.detik.com/sport-lain/d-8649669/kalah-di-perempatfinal-avc-beach-continental-ini-kata-bintang-sofyan
  [63/100] https://sport.detik.com/sport-lain/d-8649199/wec-2026-paruh-kedua-musim-dimulai-team-wrt-32-lebih-pede
  [64/100] https://sport.detik.com/raket/d-8649186/mens-world-tennis-championship-ganda-indonesia-tembus-final
  [65/100] https://sport.detik.com/sport-lain/d-8649165/bali-bakal-gelar-turnamen-catur-internasional-akhir-oktober
  [66/100] https://sport.detik.com/fotosport/d-8648227/kyrchyn-gorge-jadi-panggung-world-nomad-games
  [67/100] https://sport.detik.com/raket/d-8649124/hasil-china-masters-2026-sabar-reza-out-wakil-indonesia-habis
  [68/100] https://sport.detik.com/moto-gp/d-8648849/pol-acosta-akan-menang-balapan-dan-jadi-juara-dunia-cuma-soal-waktu
  [69/100] https://sport.detik.com/sport-lain/d-8648336/avc-continental-2026-bintang-sofyan-hadapi-selandia-baru-di-16-besar
Artikel baru dari halaman ini: 17

Mengambil halaman 3:
https://sport.detik.com/indeks?page=3
Status: 200
  [70/100] https://sport.detik.com/sportstyle/d-8647385/belum-pernah-ikut-kelas-yoga-yoga-outdoor-ini-cocok-untuk-beginner
  [71/100] https://sport.detik.com/raket/d-8647457/mens-world-tennis-championship-nathan-barki-ke-perempatfinal
  [72/100] https://sport.detik.com/sportstyle/d-8647394/bakal-ada-jakarta-vertical-run-2026-bulan-november
  [73/100] https://sport.detik.com/raket/d-8647441/hasil-china-masters-2026-sabar-reza-menang-melaju-ke-perempatfinal
  [74/100] https://sport.detik.com/sport-lain/d-8647346/dki-jakarta-gelar-pon-pantai-2026-bulan-november
  [75/100] https://sport.detik.com/moto-gp/d-8647200/marc-marquez-makin-dekat-jorge-martin-akan-lawan
  [76/100] https://sport.detik.com/moto-gp/d-8646970/gelar-juara-motogp-2026-jadi-ujian-ketahanan-marc-marquez
  [77/100] https://sport.detik.com/raket/d-8647100/hasil-china-masters-2026-leo-daniel-kena-comeback-keok-di-16-besar
  [78/100] https://sport.detik.com/sport-lain/d-8646915/kolaborasi-dengan-npc-kemenpora-genjot-pembinaan-atlet-disabilitas
  [79/100] https://sport.detik.com/sport-lain/d-8646269/jalan-panjang-bilal-hasan-menuju-titel-ufc
  [80/100] https://sport.detik.com/raket/d-8646249/hasil-china-masters-2026-jojo-terhenti-di-babak-kedua
  [81/100] https://sport.detik.com/sportstyle/d-8645952/spesialnya-jakarta-international-10k-tahun-ini
  [82/100] https://sport.detik.com/raket/d-8645946/mens-world-tennis-championship-rafalentino-dan-anthony-ke-babak-kedua
  [83/100] https://sport.detik.com/g-sport/d-8645920/atlet-bukan-satu-satunya-kunci-kemajuan-olahraga-nasional
  [84/100] https://sport.detik.com/moto-gp/d-8645850/agar-motogp-indonesia-2026-sukses-di-dalam-dan-luar-lintasan
  [85/100] https://sport.detik.com/moto-gp/d-8645527/motogp-2026-aprilia-kian-termotivasi-kalahkan-marc-marquez
  [86/100] https://sport.detik.com/raket/d-8645423/hasil-china-masters-2026-sabar-reza-menang-dua-gim-langsung
  [87/100] https://sport.detik.com/moto-gp/d-8644946/francesco-bagnaia-di-titik-terendah
  [88/100] https://sport.detik.com/raket/d-8644579/ini-dia-20-pebulutangkis-indonesia-di-asian-games-2026
Artikel baru dari halaman ini: 19

Mengambil halaman 4:
https://sport.detik.com/indeks?page=4
Status: 200
  [89/100] https://sport.detik.com/sport-lain/d-8644322/ketum-koni-pusat-sambut-positif-kejuaraan-pacu-kuda-di-aceh
  [90/100] https://sport.detik.com/sport-lain/d-8644288/pordasi-akan-optimalkan-lapangan-h-m-hasan-gayo-untuk-olahraga-berkuda
  [91/100] https://sport.detik.com/sportstyle/d-8644207/mangkuluhur-cup-ketika-golf-bukan-lagi-sekadar-olahraga
  [92/100] https://sport.detik.com/raket/d-8644222/mens-world-tennis-championship-nathan-barki-lolos-ke-babak-kedua
  [93/100] https://sport.detik.com/moto-gp/d-8643938/kampiun-motogp-2026-bukan-yang-paling-banyak-menang-tapi-paling-tenang
  [94/100] https://sport.detik.com/moto-gp/d-8644045/motogp-aragon-selesai-ini-nama-pemenang-bold-riders-podium-picks
  [95/100] https://sport.detik.com/moto-gp/d-8643813/moto3-veda-ega-sudah-empat-kali-gagal-raih-poin
  [96/100] https://sport.detik.com/moto-gp/d-8643612/marc-marquez-beri-pukulan-untuk-rider-rider-aprilia
  [97/100] https://sport.detik.com/raket/d-8643860/china-masters-2026-singkirkan-unggulan-1-leo-daniel-ke-16-besar
  [98/100] https://sport.detik.com/moto-gp/d-8643496/bagnaia-kena-mental-bos-ducati-ada-masalah-fokus
  [99/100] https://sport.detik.com/sport-lain/d-8643405/abdul-kadir-karding-jadi-ketum-perbasasi-singgung-pembinaan-dan-prestasi
  [100/100] https://sport.detik.com/sport-lain/d-8643113/bukan-pukulan-hoki-yang-runtuhkan-umar-nurmagomedov
Artikel baru dari halaman ini: 12

======================================
Total URL sport.detik.com: 100
======================================

URL yang akan diproses: 100

[1/100] Mengambil berita sport...
✓ Berhasil | 2720 karakter

[2/100] Mengambil berita sport...
✓ Berhasil | 2749 karakter

[3/100] Mengambil berita sport...
✓ Berhasil | 2191 karakter

[4/100] Mengambil berita sport...
✓ Berhasil | 2239 karakter

[5/100] Mengambil berita sport...
✓ Berhasil | 3619 karakter

[6/100] Mengambil berita sport...
✓ Berhasil | 2503 karakter

[7/100] Mengambil berita sport...
✓ Berhasil | 2332 karakter

[8/100] Mengambil berita sport...
✓ Berhasil | 3004 karakter

[9/100] Mengambil berita sport...
✓ Berhasil | 1608 karakter

[10/100] Mengambil berita sport...
✓ Berhasil | 3235 karakter

[11/100] Mengambil berita sport...
✓ Berhasil | 1557 karakter

[12/100] Mengambil berita sport...
✓ Berhasil | 2194 karakter

[13/100] Mengambil berita sport...
✓ Berhasil | 4587 karakter

[14/100] Mengambil berita sport...
✓ Berhasil | 2948 karakter

[15/100] Mengambil berita sport...
✓ Berhasil | 1400 karakter

[16/100] Mengambil berita sport...
✓ Berhasil | 3345 karakter

[17/100] Mengambil berita sport...
✓ Berhasil | 1712 karakter

[18/100] Mengambil berita sport...
✓ Berhasil | 1818 karakter

[19/100] Mengambil berita sport...
✓ Berhasil | 2006 karakter

[20/100] Mengambil berita sport...
✓ Berhasil | 1882 karakter

[21/100] Mengambil berita sport...
✓ Berhasil | 2587 karakter

[22/100] Mengambil berita sport...
✓ Berhasil | 1865 karakter

[23/100] Mengambil berita sport...
✓ Berhasil | 1837 karakter

[24/100] Mengambil berita sport...
✓ Berhasil | 1698 karakter

[25/100] Mengambil berita sport...
✓ Berhasil | 2064 karakter

[26/100] Mengambil berita sport...
✓ Berhasil | 2864 karakter

[27/100] Mengambil berita sport...
✓ Berhasil | 1801 karakter

[28/100] Mengambil berita sport...
✓ Berhasil | 1354 karakter

[29/100] Mengambil berita sport...
✓ Berhasil | 2457 karakter

[30/100] Mengambil berita sport...
✓ Berhasil | 1830 karakter

[31/100] Mengambil berita sport...
✓ Berhasil | 1941 karakter

[32/100] Mengambil berita sport...
✓ Berhasil | 135 karakter

[33/100] Mengambil berita sport...
✓ Berhasil | 2679 karakter

[34/100] Mengambil berita sport...
✓ Berhasil | 2057 karakter

[35/100] Mengambil berita sport...
✓ Berhasil | 1272 karakter

[36/100] Mengambil berita sport...
✓ Berhasil | 1867 karakter

[37/100] Mengambil berita sport...
✓ Berhasil | 1657 karakter

[38/100] Mengambil berita sport...
✓ Berhasil | 4151 karakter

[39/100] Mengambil berita sport...
✓ Berhasil | 1687 karakter

[40/100] Mengambil berita sport...
✓ Berhasil | 1766 karakter

[41/100] Mengambil berita sport...
✓ Berhasil | 2495 karakter

[42/100] Mengambil berita sport...
✓ Berhasil | 1875 karakter

[43/100] Mengambil berita sport...
✓ Berhasil | 2789 karakter

[44/100] Mengambil berita sport...
✓ Berhasil | 1403 karakter

[45/100] Mengambil berita sport...
✓ Berhasil | 4504 karakter

[46/100] Mengambil berita sport...
✓ Berhasil | 1972 karakter

[47/100] Mengambil berita sport...
✓ Berhasil | 1940 karakter

[48/100] Mengambil berita sport...
✓ Berhasil | 1657 karakter

[49/100] Mengambil berita sport...
✓ Berhasil | 2417 karakter

[50/100] Mengambil berita sport...
✓ Berhasil | 2285 karakter

[51/100] Mengambil berita sport...
✓ Berhasil | 1255 karakter

[52/100] Mengambil berita sport...
✓ Berhasil | 2083 karakter

[53/100] Mengambil berita sport...
✓ Berhasil | 3371 karakter

[54/100] Mengambil berita sport...
✓ Berhasil | 1589 karakter

[55/100] Mengambil berita sport...
✓ Berhasil | 2708 karakter

[56/100] Mengambil berita sport...
✓ Berhasil | 2643 karakter

[57/100] Mengambil berita sport...
✓ Berhasil | 2619 karakter

[58/100] Mengambil berita sport...
✓ Berhasil | 2989 karakter

[59/100] Mengambil berita sport...
✓ Berhasil | 2707 karakter

[60/100] Mengambil berita sport...
✓ Berhasil | 3894 karakter

[61/100] Mengambil berita sport...
✓ Berhasil | 2952 karakter

[62/100] Mengambil berita sport...
✓ Berhasil | 2217 karakter

[63/100] Mengambil berita sport...
✓ Berhasil | 2334 karakter

[64/100] Mengambil berita sport...
✓ Berhasil | 2710 karakter

[65/100] Mengambil berita sport...
✓ Berhasil | 3087 karakter

[66/100] Mengambil berita sport...
✓ Berhasil | 159 karakter

[67/100] Mengambil berita sport...
✓ Berhasil | 2840 karakter

[68/100] Mengambil berita sport...
✓ Berhasil | 2061 karakter

[69/100] Mengambil berita sport...
✓ Berhasil | 2559 karakter

[70/100] Mengambil berita sport...
✓ Berhasil | 1946 karakter

[71/100] Mengambil berita sport...
✓ Berhasil | 2415 karakter

[72/100] Mengambil berita sport...
✓ Berhasil | 3767 karakter

[73/100] Mengambil berita sport...
✓ Berhasil | 2205 karakter

[74/100] Mengambil berita sport...
✓ Berhasil | 3077 karakter

[75/100] Mengambil berita sport...
✓ Berhasil | 2494 karakter

[76/100] Mengambil berita sport...
✓ Berhasil | 2678 karakter

[77/100] Mengambil berita sport...
✓ Berhasil | 2101 karakter

[78/100] Mengambil berita sport...
✓ Berhasil | 5939 karakter

[79/100] Mengambil berita sport...
✓ Berhasil | 1757 karakter

[80/100] Mengambil berita sport...
✓ Berhasil | 1447 karakter

[81/100] Mengambil berita sport...
✓ Berhasil | 4511 karakter

[82/100] Mengambil berita sport...
✓ Berhasil | 2311 karakter

[83/100] Mengambil berita sport...
✓ Berhasil | 2230 karakter

[84/100] Mengambil berita sport...
✓ Berhasil | 3770 karakter

[85/100] Mengambil berita sport...
✓ Berhasil | 2114 karakter

[86/100] Mengambil berita sport...
✓ Berhasil | 1611 karakter

[87/100] Mengambil berita sport...
✓ Berhasil | 1759 karakter

[88/100] Mengambil berita sport...
✓ Berhasil | 2648 karakter

[89/100] Mengambil berita sport...
✓ Berhasil | 3004 karakter

[90/100] Mengambil berita sport...
✓ Berhasil | 2788 karakter

[91/100] Mengambil berita sport...
✓ Berhasil | 3489 karakter

[92/100] Mengambil berita sport...
✓ Berhasil | 2381 karakter

[93/100] Mengambil berita sport...
✓ Berhasil | 2011 karakter

[94/100] Mengambil berita sport...
✓ Berhasil | 2769 karakter

[95/100] Mengambil berita sport...
✓ Berhasil | 2002 karakter

[96/100] Mengambil berita sport...
✓ Berhasil | 1841 karakter

[97/100] Mengambil berita sport...
✓ Berhasil | 2354 karakter

[98/100] Mengambil berita sport...
✓ Berhasil | 2029 karakter

[99/100] Mengambil berita sport...
✓ Berhasil | 3397 karakter

[100/100] Mengambil berita sport...
✓ Berhasil | 2143 karakter

======================================
Berita sport berhasil: 100
======================================

In [24]:
data_finance = crawling_kategori(
    finance_url,
    "finance.detik.com",
    "finance",
    100
)

======================================
CRAWLING FINANCE
Target: 100 berita
======================================

Mengambil artikel dari: https://finance.detik.com/

Mengambil halaman 1:
https://finance.detik.com/
Status: 200
  [1/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653106/bandara-soetta-husein-dibuka-lagi-radin-inten-masih-ditutup
  [2/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8652990/pramono-mau-terbitkan-obligasi-purbaya-kalau-uangnya-banyak-buat-apa-utang
  [3/100] https://finance.detik.com/moneter/d-8652973/muncul-isu-gaji-asn-dipindah-ke-bank-bumn-purbaya-buka-suara
  [4/100] https://finance.detik.com/energi/d-8652949/terindikasi-isi-bbm-berulang-5-000-nomor-polisi-kendaraan-diajukan-blokir
  [5/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8652862/7-bandara-ditutup-hingga-23-59-wib-ini-daftarnya
  [6/100] https://finance.detik.com/infrastruktur/d-8654568/513-9-km-listrik-aliran-atas-krl-jabodetabek-dirawat-ini-prosesnya
  [7/100] https://finance.detik.com/infrastruktur/d-8640936/154-gardu-perlintasan-sebidang-dibangun-buat-cegah-kecelakaan
  [8/100] https://finance.detik.com/infrastruktur/d-8633294/kai-poles-stasiun-cikampek-begini-hasilnya
  [9/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654602/masih-bingung-kelola-arus-kas-bisnis-jasamu-ikut-program-ini-solusinya
  [10/100] https://finance.detik.com/energi/d-8654538/sampah-kini-disulap-jadi-bensin-dan-solar
  [11/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654509/sudah-lulus-brevet-pajak-ab-saatnya-lanjut-brevet-c-untuk-cv-lebih-kuat
  [12/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654502/perusahaan-multinasional-butuh-staf-paham-pajak-lintas-negara-belajar-di-sini
  [13/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654488/purbaya-terjunkan-anak-buah-awasi-ketat-dapur-mbg
  [14/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654444/pemda-bisa-pinjam-ke-smi-bayarnya-pakai-dbh
  [15/100] https://finance.detik.com/moneter/d-8654414/purbaya-sebut-bank-ri-siap-pungut-pajak-transaksi-digital-luar-negeri
  [16/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654391/7-rekomendasi-jasa-forwarder-import-barang-dari-china-ke-indonesia
  [17/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7390719/kisah-pilot-helikopter-banting-setir-jadi-pebisnis-teh
  [18/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7320371/panen-cuan-layanan-sayang-anabul
  [19/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7319355/menangkis-serangan-hoaks-tarik-duit-dari-bank
  [20/100] https://finance.detik.com/solusiukm/d-7309999/bisnis-kura-kura-darat-yang-bikin-dompet-gemuk
  [21/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7278891/mendulang-kasih-dan-rupiah-di-hari-raya-lewat-hampers
  [22/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7229486/ide-bisnis-lilin-aromaterapi-dari-rumah-cetak-omzet-ratusan-juta
  [23/100] https://finance.detik.com/detiktv/d-7135571/rahasia-bisnis-batik-kekinian-omzet-ratusan-juta
  [24/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7134723/rahasia-bisnis-batik-kekinian-beromzet-ratusan-juta-rupiah
  [25/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7113302/belatung-pendulang-cuan-puluhan-juta-rupiah
  [26/100] https://finance.detik.com/moneter/d-8654381/ungkap-pemda-punya-rp-100-triliun-nganggur-purbaya-ingatkan-tak-perlu-minjam
  [27/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654336/graha-merah-putih-akan-disewa-bgn-bos-telkom-hadirkan-peluang-bisnis-baru
  [28/100] https://finance.detik.com/moneter/d-8654356/penerima-bansos-bakal-dibuatkan-rekening-bank
  [29/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654315/telkomproperty-ungkap-pemanfaatan-graha-merah-putih-oleh-bgn-masih-negosiasi
  [30/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654240/harga-masker-mahal-imbas-abu-anak-krakatau-pengawasan-mesti-diperketat
  [31/100] https://finance.detik.com/energi/d-8654238/pertamina-waspada-solar-subsidi-bocor-selisih-harga-tembus-rp-18-200
  [32/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654233/tiktok-tokopedia-buka-suara-soal-kabar-blokir-tahan-saldo-seller
  [33/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654222/purbaya-ngaku-tak-pusingkan-anggaran-bgn-tahun-ini-tak-sampai-rp-200-t
  [34/100] https://finance.detik.com/bursa-dan-valas/d-8654139/ihsg-ditutup-menguat-1-ke-6-686
  [35/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654113/soal-usulan-nunggak-pajak-jadi-landasan-perampasan-aset-purbaya-bilang-gini
  [36/100] https://finance.detik.com/energi/d-8654088/bensin-campur-etanol-20-ditargetkan-jalan-2028
  [37/100] https://finance.detik.com/energi/d-8654068/terungkap-1-juta-ton-nikel-tak-bertuan-di-sulteng-bakal-dilelang
  [38/100] https://finance.detik.com/infrastruktur/d-8654044/purbaya-buka-bukaan-utang-whoosh-cicilan-rp-1-t-tenor-80-tahun
  [39/100] https://finance.detik.com/foto-bisnis/d-8653603/halim-kembali-beroperasi-mobilitas-penumpang-kembali-bergeliat
  [40/100] https://finance.detik.com/energi/d-8654009/b50-ri-bikin-jepang-malaysia-eropa-penasaran-ada-potensi-hemat-rp-170-t
  [41/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653993/bandara-soetta-sempat-ditutup-barang-ekspor-impor-rp-3-t-mandek
  [42/100] https://finance.detik.com/moneter/d-8653966/purbaya-klaim-as-tiru-ri-pindahkan-sal-ke-bank-kita-pinteran-sedikit-lah
  [43/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653958/30-barang-rampasan-negara-nggak-laku-dilelang-ini-penyebabnya
  [44/100] https://finance.detik.com/energi/d-8653920/b50-sudah-menyebar-ke-6-050-spbu-tinggal-362-masih-transisi
  [45/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653903/purbaya-cerita-omong-gede-hingga-dicap-sombong-klaim-buat-kerek-ekonomi
  [46/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653857/pengusaha-truk-sebut-aturan-zero-odol-belum-siap-di-2027-ini-alasannya
  [47/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653829/negara-kantongi-rp-26-triliun-dari-aset-rampasan
  [48/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653781/purbaya-setahun-jadi-menkeu-berat-badan-turun-sebut-ri-keluar-dari-kutukan-5
  [49/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653765/pengusaha-pertashop-minta-bisa-ikut-jual-pertalite
  [50/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653752/bantuan-beras-lanjut-hingga-desember-bulog-jamin-pasokan-cukup
  [51/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8645888/purbaya-siapkan-rp-40-t-bayar-utang-kopdes-ke-bank-bumn-jamin-tak-macet
  [52/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8645801/angka-kemiskinan-berbeda-dengan-versi-bank-dunia-bps-buka-suara
  [53/100] https://finance.detik.com/energi/d-8647759/pertamina-batalkan-rencana-beli-bbm-subsidi-tunjukkan-stnk
Artikel baru dari halaman ini: 53

Mengambil halaman 2:
https://finance.detik.com/indeks?page=2
Status: 200
  [54/100] https://finance.detik.com/moneter/d-8654026/jurus-bank-perkuat-likuiditas-bikin-pertumbuhan-bisnis-tetap-sehat
  [55/100] https://finance.detik.com/bursa-dan-valas/d-8654017/emiten-ratu-dapat-restu-terbitkan-271-juta-saham-baru
  [56/100] https://finance.detik.com/infrastruktur/d-8653955/70-negara-kumpul-di-kek-kura-kura-bali-bahas-ai-hingga-investasi
  [57/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653800/peran-pengusaha-dalam-ekonomi-nasional-didorong-makin-diperkuat
Artikel baru dari halaman ini: 4

Mengambil halaman 3:
https://finance.detik.com/indeks?page=3
Status: 200
  [58/100] https://finance.detik.com/foto-bisnis/d-8653254/kapal-logistik-tetap-beroperasi-distribusi-ke-sebesi-dan-sebuku-berjalan-normal
  [59/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653722/perkuat-customer-experience-tugu-insurance-raih-2-penghargaan-nasional
  [60/100] https://finance.detik.com/energi/d-8653695/pertashop-terancam-tutup-penjualan-pertamax-anjlok-dari-400-jadi-100-liter
  [61/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653651/harga-masker-di-pasar-pramuka-sudah-naik-2-kali-lipat
  [62/100] https://finance.detik.com/bursa-dan-valas/d-8653649/ihsg-bergerak-menguat-asing-borong-saham-bbca-bbri
  [63/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653611/harga-emas-diramal-naik-ke-rp-3-juta-lagi-ini-perkiraan-waktunya
  [64/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653574/puan-soroti-lahan-bekas-karhutla-jadi-kebun-sawit-harus-segera-diselidiki
  [65/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653551/ada-demam-masker-di-pasar-pramuka-pembeli-borong-20-box-sekaligus
  [66/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653536/harga-emas-terus-anjlok-2-kabar-ini-jadi-biang-keroknya
  [67/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653520/puan-soal-anggaran-mitigasi-bencana-ditambah-manfaatnya-harus-lebih-baik
  [68/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653500/8-bandara-terdampak-abu-vulkanik-anak-krakatau-kembali-operasi
  [69/100] https://finance.detik.com/bursa-dan-valas/d-8653498/morgan-stanley-borong-saham-goto-lagi
  [70/100] https://finance.detik.com/energi/d-8653496/ada-wacana-badan-geologi-bmkg-digabung-puan-bilang-begini
  [71/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653432/kapal-eks-kri-ki-hajar-dewantara-bakal-dilelang-rp-370-m
  [72/100] https://finance.detik.com/foto-bisnis/d-8653328/perawatan-rangkaian-diperketat-17-perjalanan-krl-bogor-line-dibatalkan
  [73/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653351/airlangga-sebut-bencana-bikin-ekonomi-kontraksi-di-daerah-terdampak
  [74/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653345/putri-mahkota-swedia-datangi-lombok-ada-apa
  [75/100] https://finance.detik.com/energi/d-8653341/investasi-energi-bersih-ri-naik-turun-esdm-ungkap-apa-yang-terjadi
  [76/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653337/dorong-kapasitas-ekspor-lpei-kemenkeu-resmikan-48-desa-devisa-di-babel
Artikel baru dari halaman ini: 19

Mengambil halaman 4:
https://finance.detik.com/indeks?page=4
Status: 200
  [77/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653305/arahan-prabowo-bantuan-beras-lanjut-sampai-desember
  [78/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653266/harga-emas-antam-hari-ini-jatuh
  [79/100] https://finance.detik.com/bursa-dan-valas/d-8653232/ihsg-dibuka-menguat-ke-6-639
  [80/100] https://finance.detik.com/bursa-dan-valas/d-8653229/dolar-as-hari-ini-menguat-ke-rp-17-646
  [81/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8652409/dari-rp-2-41-t-jadi-rp-8-51-t-mengintip-pertumbuhan-pupuk-indonesia
  [82/100] https://finance.detik.com/foto-bisnis/d-8652806/khawatir-abu-vulkanik-warga-pilih-cuci-pakaian-di-laundry-koin
  [83/100] https://finance.detik.com/bursa-dan-valas/d-8653192/simak-rekomendasi-saham-saat-ihsg-loyo
  [84/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653186/17-perjalanan-krl-dibatalkan-imbas-perawatan-armada-buatan-inka
  [85/100] https://finance.detik.com/bursa-dan-valas/d-8653180/transisi-bisnis-tbs-energi-toba-jadi-saham-hijau-pertama-bei
  [86/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653167/kemenhub-ungkap-biang-kerok-kemacetan-panjang-pelabuhan-ketapang
  [87/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653139/bandara-soetta-husein-siap-beroperasi-lagi-usai-dibuka
  [88/100] https://finance.detik.com/moneter/d-8653044/pinjaman-online-warga-ri-makin-banyak-tembus-rp-105-triliun
  [89/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653127/3-bandara-masih-ditutup-hingga-pukul-10-00-wib-ini-daftarnya
  [90/100] https://finance.detik.com/foto-bisnis/d-8652670/aktivitas-jual-beli-pasar-agung-depok-tetap-ramai-di-tengah-sebaran-abu-vulkanik
  [91/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8652992/alasan-buruh-minta-upah-naik-9-tahun-depan
  [92/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653036/tok-dpr-setujui-pagu-anggaran-kemenkeu-2027-rp-49-8-triliun
  [93/100] https://finance.detik.com/moneter/d-8653020/bos-danantara-jamin-kredit-bank-bumn-ke-kopdes-merah-putih-tak-akan-macet
  [94/100] https://finance.detik.com/moneter/d-8653006/prabowo-ingin-semua-warga-ri-punya-rekening-bank-kasih-tugas-ke-bri-bsi
Artikel baru dari halaman ini: 18

Mengambil halaman 5:
https://finance.detik.com/indeks?page=5
Status: 200
  [95/100] https://finance.detik.com/foto-bisnis/d-8652682/5-bandara-beroperasi-24-jam-usai-erupsi-anak-krakatau
  [96/100] https://finance.detik.com/foto-bisnis/d-8652179/warga-angke-terima-bantuan-beras-30-kg-jatah-untuk-tiga-bulan
  [97/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8652940/purbaya-siap-gelontorkan-dana-bencana-minta-hitungan-jangan-ngaco
  [98/100] https://finance.detik.com/infrastruktur/d-8652920/purbaya-siap-bayar-utang-kereta-cepat-uangnya-sudah-ada
  [99/100] https://finance.detik.com/foto-bisnis/d-8652281/bandara-ditutup-imbas-abu-vulkanik-kai-tambah-perjalanan-kereta-dari-jakarta
  [100/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8652879/menhub-ungkap-alasan-penutupan-7-bandara-diperpanjang
Artikel baru dari halaman ini: 6

======================================
Total URL finance.detik.com: 100
======================================

URL yang akan diproses: 100

[1/100] Mengambil berita finance...
✓ Berhasil | 2459 karakter

[2/100] Mengambil berita finance...
✓ Berhasil | 2758 karakter

[3/100] Mengambil berita finance...
✓ Berhasil | 2137 karakter

[4/100] Mengambil berita finance...
✓ Berhasil | 4664 karakter

[5/100] Mengambil berita finance...
✓ Berhasil | 2588 karakter

[6/100] Mengambil berita finance...
✓ Berhasil | 3097 karakter

[7/100] Mengambil berita finance...
✓ Berhasil | 3799 karakter

[8/100] Mengambil berita finance...
✓ Berhasil | 3067 karakter

[9/100] Mengambil berita finance...
✓ Berhasil | 1906 karakter

[10/100] Mengambil berita finance...
✓ Berhasil | 3901 karakter

[11/100] Mengambil berita finance...
✓ Berhasil | 2089 karakter

[12/100] Mengambil berita finance...
✓ Berhasil | 2139 karakter

[13/100] Mengambil berita finance...
✓ Berhasil | 1982 karakter

[14/100] Mengambil berita finance...
✓ Berhasil | 1575 karakter

[15/100] Mengambil berita finance...
✓ Berhasil | 1684 karakter

[16/100] Mengambil berita finance...
✓ Berhasil | 5977 karakter

[17/100] Mengambil berita finance...
✓ Berhasil | 1280 karakter

[18/100] Mengambil berita finance...
✓ Berhasil | 1126 karakter

[19/100] Mengambil berita finance...
✓ Berhasil | 1042 karakter

[20/100] Mengambil berita finance...
✓ Berhasil | 7013 karakter

[21/100] Mengambil berita finance...
✓ Berhasil | 1148 karakter

[22/100] Mengambil berita finance...
✓ Berhasil | 1293 karakter

[23/100] Mengambil berita finance...
✓ Berhasil | 526 karakter

[24/100] Mengambil berita finance...
✓ Berhasil | 980 karakter

[25/100] Mengambil berita finance...
✓ Berhasil | 946 karakter

[26/100] Mengambil berita finance...
✓ Berhasil | 2659 karakter

[27/100] Mengambil berita finance...
✓ Berhasil | 2851 karakter

[28/100] Mengambil berita finance...
✓ Berhasil | 2214 karakter

[29/100] Mengambil berita finance...
✓ Berhasil | 2210 karakter

[30/100] Mengambil berita finance...
✓ Berhasil | 2405 karakter

[31/100] Mengambil berita finance...
✓ Berhasil | 1845 karakter

[32/100] Mengambil berita finance...
✓ Berhasil | 3391 karakter

[33/100] Mengambil berita finance...
✓ Berhasil | 2120 karakter

[34/100] Mengambil berita finance...
✓ Berhasil | 1163 karakter

[35/100] Mengambil berita finance...
✓ Berhasil | 2526 karakter

[36/100] Mengambil berita finance...
✓ Berhasil | 2591 karakter

[37/100] Mengambil berita finance...
✓ Berhasil | 2388 karakter

[38/100] Mengambil berita finance...
✓ Berhasil | 2902 karakter

[39/100] Mengambil berita finance...
✓ Berhasil | 151 karakter

[40/100] Mengambil berita finance...
✓ Berhasil | 3215 karakter

[41/100] Mengambil berita finance...
✓ Berhasil | 3600 karakter

[42/100] Mengambil berita finance...
✓ Berhasil | 2552 karakter

[43/100] Mengambil berita finance...
✓ Berhasil | 2902 karakter

[44/100] Mengambil berita finance...
✓ Berhasil | 2137 karakter

[45/100] Mengambil berita finance...
✓ Berhasil | 2503 karakter

[46/100] Mengambil berita finance...
✓ Berhasil | 3027 karakter

[47/100] Mengambil berita finance...
✓ Berhasil | 2512 karakter

[48/100] Mengambil berita finance...
✓ Berhasil | 2148 karakter

[49/100] Mengambil berita finance...
✓ Berhasil | 2381 karakter

[50/100] Mengambil berita finance...
✓ Berhasil | 3052 karakter

[51/100] Mengambil berita finance...
✓ Berhasil | 1622 karakter

[52/100] Mengambil berita finance...
✓ Berhasil | 4337 karakter

[53/100] Mengambil berita finance...
✓ Berhasil | 2393 karakter

[54/100] Mengambil berita finance...
✓ Berhasil | 2019 karakter

[55/100] Mengambil berita finance...
✓ Berhasil | 1965 karakter

[56/100] Mengambil berita finance...
✓ Berhasil | 4760 karakter

[57/100] Mengambil berita finance...
✓ Berhasil | 3196 karakter

[58/100] Mengambil berita finance...
✓ Berhasil | 170 karakter

[59/100] Mengambil berita finance...
✓ Berhasil | 2819 karakter

[60/100] Mengambil berita finance...
✓ Berhasil | 2574 karakter

[61/100] Mengambil berita finance...
✓ Berhasil | 4587 karakter

[62/100] Mengambil berita finance...
✓ Berhasil | 1611 karakter

[63/100] Mengambil berita finance...
✓ Berhasil | 2753 karakter

[64/100] Mengambil berita finance...
✓ Berhasil | 2806 karakter

[65/100] Mengambil berita finance...
✓ Berhasil | 3027 karakter

[66/100] Mengambil berita finance...
✓ Berhasil | 2449 karakter

[67/100] Mengambil berita finance...
✓ Berhasil | 2301 karakter

[68/100] Mengambil berita finance...
✓ Berhasil | 1833 karakter

[69/100] Mengambil berita finance...
✓ Berhasil | 1471 karakter

[70/100] Mengambil berita finance...
✓ Berhasil | 2287 karakter

[71/100] Mengambil berita finance...
✓ Berhasil | 2108 karakter

[72/100] Mengambil berita finance...
✓ Berhasil | 151 karakter

[73/100] Mengambil berita finance...
✓ Berhasil | 2909 karakter

[74/100] Mengambil berita finance...
✓ Berhasil | 2699 karakter

[75/100] Mengambil berita finance...
✓ Berhasil | 3987 karakter

[76/100] Mengambil berita finance...
✓ Berhasil | 4896 karakter

[77/100] Mengambil berita finance...
✓ Berhasil | 2129 karakter

[78/100] Mengambil berita finance...
✓ Berhasil | 1939 karakter

[79/100] Mengambil berita finance...
✓ Berhasil | 1080 karakter

[80/100] Mengambil berita finance...
✓ Berhasil | 964 karakter

[81/100] Mengambil berita finance...
✓ Berhasil | 8456 karakter

[82/100] Mengambil berita finance...
✓ Berhasil | 130 karakter

[83/100] Mengambil berita finance...
✓ Berhasil | 5425 karakter

[84/100] Mengambil berita finance...
✓ Berhasil | 2788 karakter

[85/100] Mengambil berita finance...
✓ Berhasil | 4967 karakter

[86/100] Mengambil berita finance...
✓ Berhasil | 3495 karakter

[87/100] Mengambil berita finance...
✓ Berhasil | 3008 karakter

[88/100] Mengambil berita finance...
✓ Berhasil | 1737 karakter

[89/100] Mengambil berita finance...
✓ Berhasil | 3121 karakter

[90/100] Mengambil berita finance...
✓ Berhasil | 156 karakter

[91/100] Mengambil berita finance...
✓ Berhasil | 3661 karakter

[92/100] Mengambil berita finance...
✓ Berhasil | 2283 karakter

[93/100] Mengambil berita finance...
✓ Berhasil | 1974 karakter

[94/100] Mengambil berita finance...
✓ Berhasil | 2729 karakter

[95/100] Mengambil berita finance...
✓ Berhasil | 144 karakter

[96/100] Mengambil berita finance...
✓ Berhasil | 148 karakter

[97/100] Mengambil berita finance...
✓ Berhasil | 1283 karakter

[98/100] Mengambil berita finance...
✓ Berhasil | 2567 karakter

[99/100] Mengambil berita finance...
✓ Berhasil | 146 karakter

[100/100] Mengambil berita finance...
✓ Berhasil | 3495 karakter

======================================
Berita finance berhasil: 100
======================================

## 13. Menggabungkan Data

Setelah proses crawling kategori Sport dan Finance selesai, kedua dataset digabungkan menjadi satu variabel bernama `semua_data`.

Penggabungan dilakukan agar seluruh berita dapat disimpan dalam satu file dataset.

Jika masing-masing kategori berhasil mendapatkan 100 berita, maka jumlah keseluruhan data adalah:

- Sport = 100 berita
- Finance = 100 berita
- Total = 200 berita

In [25]:
semua_data = (
    data_sport +
    data_finance
)

print("Total data:", len(semua_data))

Total data: 200

## 14. Menyimpan Dataset ke CSV

Data hasil crawling selanjutnya disimpan ke dalam file CSV dengan nama `dataset_berita.csv`.

Format CSV dipilih karena mudah digunakan dan dapat dibuka menggunakan berbagai aplikasi seperti Microsoft Excel, Google Sheets, maupun Python.

Dataset terdiri dari tiga kolom:

| Kolom | Keterangan |
|---|---|
| `id` | Nomor identitas data |
| `isi_berita` | Teks atau isi berita |
| `label` | Kategori berita |

Kolom `id` dibuat secara berurutan mulai dari angka 1.

In [26]:
with open(
    "dataset_berita.csv",
    "w",
    newline="",
    encoding="utf-8-sig"
) as file:

    writer = csv.writer(file)

    writer.writerow([
        "id",
        "isi_berita",
        "label"
    ])

    for i, berita in enumerate(
        semua_data,
        start=1
    ):

        writer.writerow([
            i,
            berita["isi_berita"],
            berita["label"]
        ])

print("Dataset berhasil disimpan sebagai dataset_berita.csv")

Dataset berhasil disimpan sebagai dataset_berita.csv

## 15. Hasil Crawling

Tahap terakhir adalah menampilkan ringkasan hasil proses crawling.

Informasi yang ditampilkan meliputi jumlah berita yang berhasil dikumpulkan dari setiap kategori, jumlah keseluruhan data, serta nama file dataset yang telah dibuat.

Apabila seluruh target berhasil dicapai, maka jumlah data yang dihasilkan adalah:

```text
Sport    : 100 berita
Finance  : 100 berita
Total    : 200 berita

In [27]:

# 31. Code Cell — Hasil Akhir

print("======================================")
print("        CRAWLING SELESAI")
print("======================================")

print("Data Sport   :", len(data_sport))
print("Data Finance :", len(data_finance))
print("Total Data   :", len(semua_data))
print("File         : dataset_berita.csv")

print("======================================")

======================================
        CRAWLING SELESAI
======================================
Data Sport   : 100
Data Finance : 100
Total Data   : 200
File         : dataset_berita.csv
======================================

## 16. Menampilkan Data Hasil Crawling

Setelah proses crawling selesai dan dataset berhasil disimpan, kita dapat melihat sebagian data yang telah berhasil dikumpulkan.

Pada tahap ini, data ditampilkan berdasarkan kategorinya, yaitu **Sport** dan **Finance**.

Masing-masing kategori akan menampilkan 5 data pertama sebagai contoh hasil crawling. Data yang ditampilkan terdiri dari:

* `id` — nomor identitas data
* `isi_berita` — isi berita
* `label` — kategori berita

Penampilan sebagian data ini bertujuan untuk memastikan bahwa proses crawling dan penyimpanan dataset telah berjalan dengan baik.

In [28]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\acer\onedrive\documents\dokumen kuliah\semester 7\ppw\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 654.4 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/9.8 MB 891.9 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/9.8 MB 891.9 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/9.8 MB 730.4 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.8 MB 730.4 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.8 MB 730.4 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.8 MB 730.4 kB/s eta 0:00:13
   ----- ---------------------------------- 1.3/9.8 MB 560.1 kB/s eta 0:00:16
   ----- ---------------------------------- 1.3/9.8 MB 560.1 kB/s eta 0:00:16
   ----- ---------------------------------- 1.3/9.8 MB 560.1 kB/s eta 0:00:16
   ----- ---------------------------------- 1.3/9.8 MB 560.1 kB/s eta 0:00:16
   ----- ---------------------------------- 1.3/9.8 MB 560.1 kB/s eta 0:00:16
   ----- ---------------------------------- 1.3/9.8 MB 560.1 kB/s eta 0:00:16
   ------ --------------------------------- 1.6/9.8 MB 414.0 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.8 MB 414.0 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.8 MB 414.0 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.8 MB 414.0 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.8 MB 414.0 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.8 MB 414.0 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.8 MB 414.0 kB/s eta 0:00:20
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 338.4 kB/s eta 0:00:24
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 284.1 kB/s eta 0:00:28
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   --------- ------------------------------ 2.4/9.8 MB 240.0 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 213.7 kB/s eta 0:00:34
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ----------- ---------------------------- 2.9/9.8 MB 196.2 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.8 MB 187.8 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.8 MB 179.2 kB/s eta 0:00:36
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 176.6 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 169.5 kB/s eta 0:00:35
   ----------------- ---------------------- 4.2/9.8 MB 169.0 kB/s eta 0:00:34
   ----------------- ---------------------- 4.2/9.8 MB 169.0 kB/s eta 0:00:34
   ----------------- ---------------------- 4.2/9.8 MB 169.0 kB/s eta 0:00:34
   ----------------- ---------------------- 4.2/9.8 MB 169.0 kB/s eta 0:00:34
   ----------------- ---------------------- 4.2/9.8 MB 169.0 kB/s eta 0:00:34
   ----------------- ---------------------- 4.2/9.8 MB 169.0 kB/s eta 0:00:34
   ----------------- ---------------------- 4.2/9.8 MB 169.0 kB/s eta 0:00:34
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 170.0 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 163.1 kB/s eta 0:00:32
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   -------------------- ------------------- 5.0/9.8 MB 150.5 kB/s eta 0:00:33
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   --------------------- ------------------ 5.2/9.8 MB 122.4 kB/s eta 0:00:38
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ---------------------- ----------------- 5.5/9.8 MB 112.9 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ----------------------- ---------------- 5.8/9.8 MB 106.3 kB/s eta 0:00:39
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------ --------------- 6.0/9.8 MB 105.6 kB/s eta 0:00:36
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   ------------------------- -------------- 6.3/9.8 MB 106.1 kB/s eta 0:00:34
   -------------------------- ------------- 6.6/9.8 MB 107.6 kB/s eta 0:00:31
   -------------------------- ------------- 6.6/9.8 MB 107.6 kB/s eta 0:00:31
   -------------------------- ------------- 6.6/9.8 MB 107.6 kB/s eta 0:00:31
   -------------------------- ------------- 6.6/9.8 MB 107.6 kB/s eta 0:00:31
   -------------------------- ------------- 6.6/9.8 MB 107.6 kB/s eta 0:00:31
   -------------------------- ------------- 6.6/9.8 MB 107.6 kB/s eta 0:00:31
   -------------------------- ------------- 6.6/9.8 MB 107.6 kB/s eta 0:00:31
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   --------------------------- ------------ 6.8/9.8 MB 108.7 kB/s eta 0:00:28
   ---------------------------- ----------- 7.1/9.8 MB 108.5 kB/s eta 0:00:26
   ---------------------------- ----------- 7.1/9.8 MB 108.5 kB/s eta 0:00:26
   ---------------------------- ----------- 7.1/9.8 MB 108.5 kB/s eta 0:00:26

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import pandas as pd

# Membaca dataset hasil crawling
df = pd.read_csv("dataset_berita.csv")

print("Jumlah seluruh data:", len(df))

Jumlah seluruh data: 200

In [32]:
print("===== 5 DATA SPORT =====")

display(
    df[df["label"] == "sport"][
        ["id", "isi_berita", "label"]
    ].head(5)
)

print("\n===== 5 DATA FINANCE =====")

display(
    df[df["label"] == "finance"][
        ["id", "isi_berita", "label"]
    ].head(5)
)

===== 5 DATA SPORT =====

   id                                         isi_berita  label
0   1  Jakarta - Putri Kusuma Wardani percaya diri de...  sport
1   2  Jakarta - Mata Derrick Michael Xzavierro berbi...  sport
2   3  Jakarta - Marc Marquez masih harus beradaptasi...  sport
3   4  Jakarta - Momen debut di Asian Games 2026 tak ...  sport
4   5  Jakarta - MotoGP 2026 akan berlanjut ke San Ma...  sport

===== 5 DATA FINANCE =====

      id                                         isi_berita    label
100  101  Jakarta - Penutupan operasional Bandara Soekar...  finance
101  102  Jakarta - Menteri Keuangan (Menkeu) Purbaya Yu...  finance
102  103  Jakarta - Menteri Keuangan Purbaya Yudhi Sadew...  finance
103  104  Jakarta - PT Pertamina Patra Niaga memperkuat ...  finance
104  105  Jakarta - AirNav Indonesia kembali memperbarui...  finance